#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_HomeWork
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbDemo")]
	public partial class dbDemoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InserttCustomer(tCustomer instance);
    partial void UpdatetCustomer(tCustomer instance);
    partial void DeletetCustomer(tCustomer instance);
    partial void InserttMessage(tMessage instance);
    partial void UpdatetMessage(tMessage instance);
    partial void DeletetMessage(tMessage instance);
    #endregion
		
		public dbDemoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbDemoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tCustomer> tCustomer
		{
			get
			{
				return this.GetTable<tCustomer>();
			}
		}
		
		public System.Data.Linq.Table<tMessage> tMessage
		{
			get
			{
				return this.GetTable<tMessage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tCustomer")]
	public partial class tCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fId;
		
		private string _fName;
		
		private string _fPhone;
		
		private string _fAddress;
		
		private string _fEmail;
		
		private string _fPassword;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIdChanging(int value);
    partial void OnfIdChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OnfPhoneChanging(string value);
    partial void OnfPhoneChanged();
    partial void OnfAddressChanging(string value);
    partial void OnfAddressChanged();
    partial void OnfEmailChanging(string value);
    partial void OnfEmailChanged();
    partial void OnfPasswordChanging(string value);
    partial void OnfPasswordChanged();
    #endregion
		
		public tCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fId
		{
			get
			{
				return this._fId;
			}
			set
			{
				if ((this._fId != value))
				{
					this.OnfIdChanging(value);
					this.SendPropertyChanging();
					this._fId = value;
					this.SendPropertyChanged("fId");
					this.OnfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="NVarChar(50)")]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this.OnfNameChanging(value);
					this.SendPropertyChanging();
					this._fName = value;
					this.SendPropertyChanged("fName");
					this.OnfNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPhone", DbType="NVarChar(50)")]
		public string fPhone
		{
			get
			{
				return this._fPhone;
			}
			set
			{
				if ((this._fPhone != value))
				{
					this.OnfPhoneChanging(value);
					this.SendPropertyChanging();
					this._fPhone = value;
					this.SendPropertyChanged("fPhone");
					this.OnfPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAddress", DbType="NVarChar(50)")]
		public string fAddress
		{
			get
			{
				return this._fAddress;
			}
			set
			{
				if ((this._fAddress != value))
				{
					this.OnfAddressChanging(value);
					this.SendPropertyChanging();
					this._fAddress = value;
					this.SendPropertyChanged("fAddress");
					this.OnfAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fEmail", DbType="NVarChar(50)")]
		public string fEmail
		{
			get
			{
				return this._fEmail;
			}
			set
			{
				if ((this._fEmail != value))
				{
					this.OnfEmailChanging(value);
					this.SendPropertyChanging();
					this._fEmail = value;
					this.SendPropertyChanged("fEmail");
					this.OnfEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPassword", DbType="NVarChar(50)")]
		public string fPassword
		{
			get
			{
				return this._fPassword;
			}
			set
			{
				if ((this._fPassword != value))
				{
					this.OnfPasswordChanging(value);
					this.SendPropertyChanging();
					this._fPassword = value;
					this.SendPropertyChanged("fPassword");
					this.OnfPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMessage")]
	public partial class tMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fIndex;
		
		private System.Nullable<int> _fId;
		
		private string _fName;
		
		private string _fDate;
		
		private string _fMessage;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIndexChanging(int value);
    partial void OnfIndexChanged();
    partial void OnfIdChanging(System.Nullable<int> value);
    partial void OnfIdChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OnfDateChanging(string value);
    partial void OnfDateChanged();
    partial void OnfMessageChanging(string value);
    partial void OnfMessageChanged();
    #endregion
		
		public tMessage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fIndex", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fIndex
		{
			get
			{
				return this._fIndex;
			}
			set
			{
				if ((this._fIndex != value))
				{
					this.OnfIndexChanging(value);
					this.SendPropertyChanging();
					this._fIndex = value;
					this.SendPropertyChanged("fIndex");
					this.OnfIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", DbType="Int")]
		public System.Nullable<int> fId
		{
			get
			{
				return this._fId;
			}
			set
			{
				if ((this._fId != value))
				{
					this.OnfIdChanging(value);
					this.SendPropertyChanging();
					this._fId = value;
					this.SendPropertyChanged("fId");
					this.OnfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="NVarChar(50)")]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this.OnfNameChanging(value);
					this.SendPropertyChanging();
					this._fName = value;
					this.SendPropertyChanged("fName");
					this.OnfNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDate", DbType="NVarChar(50)")]
		public string fDate
		{
			get
			{
				return this._fDate;
			}
			set
			{
				if ((this._fDate != value))
				{
					this.OnfDateChanging(value);
					this.SendPropertyChanging();
					this._fDate = value;
					this.SendPropertyChanged("fDate");
					this.OnfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fMessage", DbType="NVarChar(150)")]
		public string fMessage
		{
			get
			{
				return this._fMessage;
			}
			set
			{
				if ((this._fMessage != value))
				{
					this.OnfMessageChanging(value);
					this.SendPropertyChanging();
					this._fMessage = value;
					this.SendPropertyChanged("fMessage");
					this.OnfMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
